# Generated by Django 2.2.7 on 2019-11-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_no', models.CharField(max_length=10)),
                ('slot_no', models.CharField(max_length=10)),
                ('seat_no', models.CharField(max_length=10)),
                ('empty', models.BooleanField()),
            ],
        ),
    ]
